/**
 * Registry for assets embedded into a `bun build --compile` binary.
 *
 * The release entrypoint (generated by scripts/gen-embedded-entry.ts, not
 * checked in) imports every Studio export file and drizzle migration with
 * `with { type: 'file' }` — Bun embeds them and the import yields a virtual
 * path readable via Bun.file — and registers the path maps here BEFORE the
 * daemon boots. Running from source leaves the registry empty and the disk
 * paths are used as before.
 */

export interface EmbeddedAssets {
  /** Studio static export: relative URL path (e.g. `_next/static/x.js`) → embedded path. */
  studio: Record<string, string>
  /** Drizzle migrations: path relative to drizzle/ (e.g. `meta/_journal.json`) → embedded path. */
  drizzle: Record<string, string>
}

let assets: EmbeddedAssets | null = null

export function registerEmbeddedAssets(next: EmbeddedAssets): void {
  assets = next
}

export function embeddedAssets(): EmbeddedAssets | null {
  return assets
}
