import { z } from 'zod'
import { DeviceAddedMessage, DeviceDiscoveredMessage, DeviceReadinessMessage, DeviceReadinessSetMessage, DeviceRemovedMessage, DeviceStatusMessage } from './device'
import {
  DevicePairingCodeMessage,
  DevicePairingCodeResultMessage,
  DevicePairingRequestMessage,
  DevicePairingRequestResultMessage,
  DeviceUnauthorizedMessage,
  DeviceInspectorStatusMessage,
  DeviceInspectorFallbackMessage,
  DeviceBatteryMessage,
} from './messages/enroll'
import { InputGestureMessage, InputKeyMessage, InputSwipeMessage, InputTapMessage, InputTextMessage } from './messages/input'
import {
  JobArtifactMessage,
  JobCancelMessage,
  JobEnqueueMessage,
  JobLogMessage,
  JobStatusEventMessage,
  LeaseAcquiredMessage,
  LeaseAcquireMessage,
  LeaseReleasedMessage,
  LeaseReleaseMessage,
  LeaseChangedMessage,
  LeaseRevokedMessage,
  JobWaitingMessage,
} from './messages/job'
import {
  QualitySchema,
  SessionProgressMessage,
  StreamEndedMessage,
  StreamKeyframeMessage,
  StreamMetaMessage,
  StreamStartedMessage,
  StreamStartMessage,
  StreamStopMessage,
} from './messages/stream'
import {
  WebRtcAnswerMessage,
  WebRtcFailedMessage,
  WebRtcIceMessage,
  WebRtcOfferMessage,
  WebRtcRequestMessage,
  WebRtcStopMessage,
} from './tunnel'
import {
  ToolChangedMessage,
  ToolInstallProgressMessage,
  ToolProvisionProgressMessage,
} from './messages/tool'
import { BatchStatusMessage } from './messages/batch'
import { ScheduleFiredMessage } from './messages/schedule'
import { DeviceEventMessage, LogSubscribeMessage, LogUnsubscribeMessage } from './messages/device-event'
import { DeviceViewersMessage, HelloMessage, ViewerSchema } from './messages/presence'
import {
  MonitorStartMessage,
  MonitorStopMessage,
  MonitorOneshotMessage,
  MonitorStartedMessage,
  MonitorDataMessage,
  MonitorEndedMessage,
  MonitorResultMessage,
  MonitorSubscribersMessage,
  ShellExecMessage,
  ShellEchoMessage,
  ShellResultMessage,
} from './messages/shell'
import { ClipboardGetMessage, ClipboardOkMessage, ClipboardSetMessage, ClipboardValueMessage } from './messages/clipboard'
import { TransferCancelMessage, TransferDoneMessage, TransferProgressMessage } from './messages/transfer'
import {
  InspectAttachMessage,
  InspectDetachMessage,
  InspectDumpMessage,
  InspectFindMessage,
  InspectMatchMessage,
  InspectStatusMessage,
  InspectTreeMessage,
} from './messages/inspect'
import {
  AgentSubscribeMessage,
  AgentUnsubscribeMessage,
  AgentRunCancelMessage,
  AgentRunStartedMessage,
  AgentRunFinishedMessage,
  AgentDeltaMessage,
  AgentMessageAppendedMessage,
  AgentToolStartedMessage,
  AgentToolFinishedMessage,
  AgentApprovalRequestedMessage,
  AgentApprovalResolvedMessage,
  AgentChildStartedMessage,
  AgentChildFinishedMessage,
  AgentMessageQueuedMessage,
  AgentMessageDeliveredMessage,
} from './messages/agent'
import { NotificationCreatedMessage } from './messages/notify'

export { EnvelopeSchema, type Envelope } from './envelope'
export * from './api'
export {
  EffortSchema,
  AgentDefaultsSchema,
  AgentSettingsSchema,
  ResolvedAgentConfigSchema,
  WorkspaceScopeSchema,
  AgentSlugSchema,
  AgentSchema,
  AgentWriteInputSchema,
  AgentUpdateInputSchema,
  resolveAgentConfig,
  ConnectorKindSchema,
  ConnectorStatusSchema,
  ConnectorSchema,
  ConnectorWriteInputSchema,
  ConnectorUpdateInputSchema,
  ModelInfoSchema,
  ModelListResponseSchema,
  ConnectorTestResultSchema,
  type Effort,
  type AgentDefaults,
  type AgentSettings,
  type ResolvedAgentConfig,
  type WorkspaceScope,
  type Agent,
  type AgentWriteInput,
  type AgentUpdateInput,
  type ConnectorKind,
  type ConnectorStatus,
  type Connector,
  type ConnectorWriteInput,
  type ConnectorUpdateInput,
  type ModelInfo,
  type ModelListResponse,
  type ConnectorTestResult,
} from './agent'
export { normaliseTag, TagSchema } from './tags'
export { ScriptRefSchema, parseScriptRef, compareSemver, isPrereleaseVersion, type ScriptRef } from './script-ref'
export {
  CAPABILITY_REFUSAL_CODES,
  CapabilityRefusalCodeSchema,
  CapabilityErrorSchema,
  toJsonSchema,
  GestureEasingSchema,
  ScrollDirectionSchema,
  PackageNameSchema,
  TapArgsSchema,
  SwipeArgsSchema,
  ScrollArgsSchema,
  FlingArgsSchema,
  TypeArgsSchema,
  KeyArgsSchema,
  FindArgsSchema,
  DumpArgsSchema,
  WaitForArgsSchema,
  ScreenshotArgsSchema,
  AppLaunchArgsSchema,
  AppForceStopArgsSchema,
  ClipboardGetArgsSchema,
  ClipboardSetArgsSchema,
  InstallArgsSchema,
  PushArgsSchema,
  PullArgsSchema,
  DEVICE_CALL_ARGS,
  type Capability,
  type AnyCapability,
  type CapabilityResult,
  type CapabilityEffect,
  type CapabilityLease,
  type CapabilityRefusalCode,
  type CapabilityError,
  type DeviceCallMethod,
} from './capability'
export {
  DeviceStatusSchema,
  DeviceInfoSchema,
  DeviceAddedMessage,
  DeviceRemovedMessage,
  DeviceDiscoveredMessage,
  DeviceStatusMessage,
  DeviceReadinessSetMessage,
  DeviceReadinessMessage,
  LeaseHolderSchema,
  type DeviceStatus,
  type DeviceInfo,
  type DeviceAdded,
  type DeviceRemoved,
  type DeviceDiscovered,
  type DeviceStatusEvent,
  type DeviceReadinessSet,
  type DeviceReadinessEvent,
  type LeaseHolder,
} from './device'
export {
  ReadinessSchema,
  ReadinessBlockedReasonSchema,
  DeviceReadinessSchema,
  type Readiness,
  type ReadinessBlockedReason,
  type DeviceReadiness,
} from './readiness'
export type {
  Transport,
  TransportExecOptions,
  DisplaySource,
  InputSink,
  Inspector,
  Point,
  FrameMeta,
  GestureSample,
  ShellResult,
} from './driver'
export {
  EngineDescriptorSchema,
  RegistryResponseSchema,
  validateEngineSelection,
  type EngineDescriptor,
  type RegistryResponse,
  type EngineSelection,
  type EngineSelectionResult,
} from './registry'
export {
  BatteryStateSchema,
  TimingSettingsSchema,
  KeepAwakeModeSchema,
  ShellModeSchema,
  DeviceGpsSchema,
  DeviceIdentitySchema,
  DeviceSettingsSchema,
  FarmSettingsSchema,
  JobSettingsSchema,
  defaultFarmSettings,
  defaultDeviceSettings,
  type BatteryState,
  type KeepAwakeMode,
  type ShellMode,
  type TimingSettings,
  type DeviceGps,
  type DeviceIdentity,
  type DeviceSettings,
  type FarmSettings,
  type JobSettings,
  type SessionSettings,
  type WallSettings,
  type ReadinessSettings,
  type WorkspaceSettings,
} from './settings'
export {
  ToolInstallProgressMessage,
  ToolProvisionProgressMessage,
  ToolChangedMessage,
  type ToolInstallProgress,
  type ToolProvisionProgress,
  type ToolChanged,
} from './messages/tool'
export {
  NormPointSchema,
  InputTapMessage,
  InputSwipeMessage,
  InputKeyMessage,
  InputTextMessage,
  NormGestureSampleSchema,
  InputGestureMessage,
  type NormPoint,
  type NormGestureSample,
} from './messages/input'
export {
  StreamStartMessage,
  StreamStartedMessage,
  StreamStopMessage,
  StreamKeyframeMessage,
  StreamMetaMessage,
  StreamEndedMessage,
  SessionPhaseSchema,
  SessionProgressMessage,
  QualitySchema,
  type SessionPhase,
  type SessionProgress,
  type Quality,
} from './messages/stream'
export {
  DeviceUnauthorizedMessage,
  DevicePairingRequestMessage,
  DevicePairingRequestResultMessage,
  DevicePairingCodeMessage,
  DevicePairingCodeResultMessage,
  DeviceInspectorStatusMessage,
  DeviceInspectorFallbackMessage,
  DeviceBatteryMessage,
} from './messages/enroll'
export {
  CHANNEL,
  VIDEO_CODEC,
  VIDEO_FLAG_KEYFRAME,
  encodeVideoFrame,
  decodeVideoFrame,
  isH264Keyframe,
  encodeSnapshot,
  decodeSnapshot,
  type DecodedVideoFrame,
  type DecodedSnapshot,
} from './binary'
export {
  JobStatusSchema,
  SleepJobParamsSchema,
  JobInfoSchema,
  JobDetailSchema,
  ArtifactInfoSchema,
  JobLogMessage,
  JobArtifactMessage,
  JobEnqueueMessage,
  JobCancelMessage,
  JobStatusEventMessage,
  LeaseAcquireMessage,
  LeaseReleaseMessage,
  LeaseAcquiredMessage,
  LeaseReleasedMessage,
  LeaseChangedMessage,
  LeaseRevokedMessage,
  JobWaitingMessage,
  type JobStatus,
  type JobInfo,
  type JobDetail,
  type ArtifactInfo,
  type SleepJobParams,
} from './messages/job'
export {
  BatchOrderSchema,
  BatchStatusSchema,
  BatchCountsSchema,
  ClusterInfoSchema,
  ResolvedTargetSchema,
  SkippedDeviceSchema,
  ClusterPreviewSchema,
  BatchInfoSchema,
  BatchStatusMessage,
  type BatchOrder,
  type BatchStatusValue,
  type BatchCounts,
  type ClusterInfo,
  type ClusterPreview,
  type BatchInfo,
  type BatchStatusEvent,
} from './messages/batch'
export {
  OnOverlapSchema,
  CatchUpSchema,
  ScheduleRunOutcomeSchema,
  ScheduleWorkTargetSchema,
  ScheduleThreadModeSchema,
  OnApprovalRequiredSchema,
  ScheduleInfoSchema,
  ScheduleRunInfoSchema,
  ScheduleFiredMessage,
  type OnOverlap,
  type CatchUp,
  type ScheduleRunOutcome,
  type ScheduleWorkTarget,
  type ScheduleThreadMode,
  type OnApprovalRequired,
  type ScheduleInfo,
  type ScheduleRunInfo,
  type ScheduleFiredEvent,
} from './messages/schedule'
export {
  NotificationLevelSchema,
  NotificationContextSchema,
  NotificationSchema,
  NotifySendInputSchema,
  NotifySendOutputSchema,
  WebhookDeliveryStatusSchema,
  WebhookEndpointSchema,
  WebhookEndpointWriteInputSchema,
  WebhookEndpointUpdateInputSchema,
  NotificationCreatedMessage,
  type NotificationLevel,
  type NotificationContext,
  type Notification,
  type NotifySendInput,
  type NotifySendOutput,
  type WebhookDeliveryStatus,
  type WebhookEndpoint,
  type WebhookEndpointWriteInput,
  type WebhookEndpointUpdateInput,
  type NotificationCreatedEvent,
} from './messages/notify'
export {
  DeviceEventStreamSchema,
  MAIN_EVENT_KINDS,
  INPUT_EVENT_KINDS,
  DeviceEventSchema,
  LogSubscribeMessage,
  LogUnsubscribeMessage,
  DeviceEventMessage,
  type DeviceEventStream,
  type DeviceEvent,
} from './messages/device-event'
export {
  ViewerSchema,
  DeviceViewersMessage,
  HelloMessage,
  type Viewer,
  type DeviceViewersEvent,
  type HelloEvent,
} from './messages/presence'
export {
  MonitorKindSchema,
  LogcatOptionsSchema,
  EmptyMonitorOptionsSchema,
  STREAMING_MONITOR_KINDS,
  ONE_SHOT_MONITOR_KINDS,
  optionsSchemaFor,
  type MonitorKind,
  type LogcatOptions,
} from './messages/monitor'
export {
  MonitorEndReasonSchema,
  MonitorStartMessage,
  MonitorStopMessage,
  MonitorOneshotMessage,
  MonitorStartedMessage,
  MonitorDataMessage,
  MonitorEndedMessage,
  MonitorResultMessage,
  MonitorSubscribersMessage,
  ShellExecMessage,
  ShellEchoMessage,
  ShellResultMessage,
  type MonitorEndReason,
} from './messages/shell'
export {
  ClipboardGetMessage,
  ClipboardSetMessage,
  ClipboardValueMessage,
  ClipboardOkMessage,
} from './messages/clipboard'
export {
  TransferKindSchema,
  TransferProgressMessage,
  TransferDoneMessage,
  TransferCancelMessage,
  InstallJobParamsSchema,
  InstallResultSchema,
  type TransferKind,
  type InstallJobParams,
  type InstallResult,
} from './messages/transfer'
export {
  PointSchema,
  SelectorSchema,
  UiNodeSchema,
  BoundsSchema,
  KeyCodeSchema,
  KEYCODES,
  resolveKeyCode,
  type Selector,
  type UiNode,
  type Bounds,
  type KeyCode,
  type KeyName,
} from './ui-node'
export { matchSelector, centerOf } from './selector-match'
export { FindOutcomeSchema, type FindOutcome } from './find-outcome'
export {
  countMatches,
  proposeSelectors,
  type SelectorCandidate,
  type SelectorCandidateKind,
} from './selector-analysis'
export {
  InspectRequestIdSchema,
  FrameSizeSchema,
  InspectAttachMessage,
  InspectDetachMessage,
  InspectDumpMessage,
  InspectFindMessage,
  InspectStateSchema,
  InspectStatusMessage,
  InspectTreeMessage,
  InspectMatchMessage,
  type InspectState,
} from './messages/inspect'
export {
  AgentMessageRoleSchema,
  AgentTextBlockSchema,
  AgentThinkingBlockSchema,
  AgentToolUseBlockSchema,
  AgentImageMediaTypeSchema,
  AgentImageRefSchema,
  ToolResultContentSchema,
  AgentToolResultBlockSchema,
  AgentContentBlockSchema,
  AgentMessageSchema,
  AgentBlobInfoSchema,
  AgentRunStatusSchema,
  AgentStopReasonSchema,
  AgentErrorClassSchema,
  AgentUsageSchema,
  AgentThreadOriginSchema,
  AgentThreadSchema,
  AgentRunSchema,
  AgentApprovalStatusSchema,
  AgentApprovalSchema,
  CreateThreadInputSchema,
  PostThreadMessageInputSchema,
  ApprovalDecisionInputSchema,
  AgentSubscribeMessage,
  AgentUnsubscribeMessage,
  AgentRunCancelMessage,
  AgentRunStartedMessage,
  AgentRunFinishedMessage,
  AgentDeltaMessage,
  AgentMessageAppendedMessage,
  AgentToolStartedMessage,
  AgentToolFinishedMessage,
  AgentApprovalRequestedMessage,
  AgentApprovalResolvedMessage,
  AgentTreeNodeSchema,
  AgentTreeResponseSchema,
  AgentChildStartedMessage,
  AgentChildFinishedMessage,
  AgentMessageQueuedMessage,
  AgentMessageDeliveredMessage,
  type AgentMessageRole,
  type AgentImageMediaType,
  type AgentImageRef,
  type ToolResultContent,
  type AgentContentBlock,
  type AgentMessage,
  type AgentBlobInfo,
  type AgentRunStatus,
  type AgentStopReason,
  type AgentErrorClass,
  type AgentUsage,
  type AgentThreadOrigin,
  type AgentThread,
  type AgentRun,
  type AgentTreeNode,
  type AgentTreeResponse,
  type AgentApprovalStatus,
  type AgentApproval,
  type CreateThreadInput,
  type PostThreadMessageInput,
  type ApprovalDecisionInput,
} from './messages/agent'

export {
  RoutedEnvelopeSchema,
  NodeToControlSchema,
  ControlToNodeSchema,
  NodeHelloMessage,
  NodeHelloLegacyMessage,
  NodeHelloAckMessage,
  NodeDevicesMessage,
  NodeDevicesLegacyMessage,
  SessionStartMessage,
  SessionStopMessage,
  JobDispatchMessage,
  TunnelPingMessage,
  TunnelPongMessage,
  TunnelChannelOpenMessage,
  TunnelChannelCloseMessage,
  TUNNEL_FRAME_MARKER,
  encodeTunnelFrame,
  decodeTunnelFrame,
  InputForwardMessage,
  JobCancelForwardMessage,
  SessionStartedMessage,
  SessionFailedMessage,
  JobProgressMessage,
  WebRtcRequestMessage,
  WebRtcOfferMessage,
  WebRtcAnswerMessage,
  WebRtcIceMessage,
  WebRtcFailedMessage,
  WebRtcStopMessage,
  ShellReplyErrorSchema,
  ShellExecRequestMessage,
  ShellExecReplyMessage,
  ShellStreamRequestMessage,
  ShellStreamReplyMessage,
  ShellStreamStopMessage,
  ShellStreamEndedMessage,
  ClipboardReplyErrorSchema,
  ClipboardGetRequestMessage,
  ClipboardGetReplyMessage,
  ClipboardSetRequestMessage,
  ClipboardSetReplyMessage,
  type TunnelChannelKind,
  type RoutedEnvelope,
  type NodeToControl,
  type ControlToNode,
} from './tunnel'

export {
  NetworkEngineIdSchema,
  NetworkCapabilitiesSchema,
  Socks5RouteConfigSchema,
  redactRouteConfig,
  renderStickyUsername,
  NetworkCredentialSchema,
  CreateNetworkCredentialRequestSchema,
  NetworkObservationSchema,
  NetworkStatusSchema,
  PersistedNetworkRouteSchema,
  RouteCheckIdSchema,
  RouteCheckSchema,
  deriveHealth,
  GeoExpectationSchema,
  GeoObservationSchema,
  GeoProviderResponseSchema,
  matchGeoExpectation,
  EXIT_HISTORY_LIMIT,
  pushExitHistory,
  type NetworkEngineId,
  type NetworkCapabilities,
  type Socks5RouteConfig,
  type NetworkCredential,
  type CreateNetworkCredentialRequest,
  type NetworkObservation,
  type NetworkStatus,
  type PersistedNetworkRoute,
  type RouteCheckId,
  type RouteCheck,
  type GeoExpectation,
  type GeoObservation,
  type GeoProviderResponse,
  type GeoMatchResult,
} from './network'

export {
  GUEST_AGENT_SOCKET,
  GUEST_AGENT_PROTOCOL,
  GuestAgentCapabilitySchema,
  GuestAgentErrorCodeSchema,
  HelloRequestSchema,
  PingRequestSchema,
  RouteStartRequestSchema,
  RouteStopRequestSchema,
  RouteStatusRequestSchema,
  EgressProbeRequestSchema,
  RouteHoldRequestSchema,
  LocationSetRequestSchema,
  LocationClearRequestSchema,
  GuestAgentRequestSchema,
  HelloResultSchema,
  PingResultSchema,
  RouteStartResultSchema,
  RouteStopResultSchema,
  RouteStatusResultSchema,
  EgressProbeLegSchema,
  EgressProbeResultSchema,
  RouteHoldResultSchema,
  LocationSetResultSchema,
  LocationClearResultSchema,
  GuestAgentOkResponseSchema,
  GuestAgentErrorResponseSchema,
  GuestAgentResponseSchema,
  type GuestAgentCapability,
  type GuestAgentErrorCode,
  type HelloRequest,
  type PingRequest,
  type RouteStartRequest,
  type RouteStopRequest,
  type RouteStatusRequest,
  type EgressProbeRequest,
  type RouteHoldRequest,
  type LocationSetRequest,
  type LocationClearRequest,
  type GuestAgentRequest,
  type HelloResult,
  type PingResult,
  type RouteStartResult,
  type RouteStopResult,
  type RouteStatusResult,
  type EgressProbeLeg,
  type EgressProbeResult,
  type RouteHoldResult,
  type LocationSetResult,
  type LocationClearResult,
  type GuestAgentOkResponse,
  type GuestAgentErrorResponse,
  type GuestAgentResponse,
} from './guest-agent'

/** Generic server→client error (a failed reply, an invalid message). */
export const ErrorMessage = z.object({
  type: z.literal('error'),
  id: z.string().optional(),
  payload: z.object({ code: z.string(), message: z.string() }),
})

/** Every server→client message. */
export const ServerMessageSchema = z.discriminatedUnion('type', [
  HelloMessage,
  DeviceViewersMessage,
  DeviceAddedMessage,
  DeviceRemovedMessage,
  DeviceDiscoveredMessage,
  DeviceStatusMessage,
  DeviceReadinessMessage,
  DeviceUnauthorizedMessage,
  DeviceInspectorStatusMessage,
  DeviceInspectorFallbackMessage,
  DeviceBatteryMessage,
  ToolInstallProgressMessage,
  ToolProvisionProgressMessage,
  ToolChangedMessage,
  StreamStartedMessage,
  StreamMetaMessage,
  StreamEndedMessage,
  SessionProgressMessage,
  DevicePairingRequestResultMessage,
  DevicePairingCodeResultMessage,
  JobStatusEventMessage,
  JobLogMessage,
  JobArtifactMessage,
  LeaseAcquiredMessage,
  LeaseReleasedMessage,
  LeaseChangedMessage,
  LeaseRevokedMessage,
  JobWaitingMessage,
  WebRtcOfferMessage,
  WebRtcFailedMessage,
  WebRtcIceMessage,
  BatchStatusMessage,
  ScheduleFiredMessage,
  DeviceEventMessage,
  MonitorStartedMessage,
  MonitorDataMessage,
  MonitorEndedMessage,
  MonitorResultMessage,
  MonitorSubscribersMessage,
  ShellEchoMessage,
  ShellResultMessage,
  ClipboardValueMessage,
  ClipboardOkMessage,
  TransferProgressMessage,
  TransferDoneMessage,
  InspectStatusMessage,
  InspectTreeMessage,
  InspectMatchMessage,
  AgentRunStartedMessage,
  AgentRunFinishedMessage,
  AgentDeltaMessage,
  AgentMessageAppendedMessage,
  AgentToolStartedMessage,
  AgentToolFinishedMessage,
  AgentApprovalRequestedMessage,
  AgentApprovalResolvedMessage,
  AgentChildStartedMessage,
  AgentChildFinishedMessage,
  AgentMessageQueuedMessage,
  AgentMessageDeliveredMessage,
  NotificationCreatedMessage,
  ErrorMessage,
])
export type ServerMessage = z.infer<typeof ServerMessageSchema>

/** Every client→server message (M2: input, stream, pairing). */
export const ClientMessageSchema = z.discriminatedUnion('type', [
  InputTapMessage,
  InputSwipeMessage,
  InputGestureMessage,
  InputKeyMessage,
  InputTextMessage,
  StreamStartMessage,
  StreamStopMessage,
  StreamKeyframeMessage,
  DeviceReadinessSetMessage,
  DevicePairingRequestMessage,
  DevicePairingCodeMessage,
  JobEnqueueMessage,
  JobCancelMessage,
  LeaseAcquireMessage,
  LeaseReleaseMessage,
  WebRtcRequestMessage,
  WebRtcAnswerMessage,
  WebRtcStopMessage,
  // ICE is bidirectional: the browser sends its candidates too.
  WebRtcIceMessage,
  LogSubscribeMessage,
  LogUnsubscribeMessage,
  MonitorStartMessage,
  MonitorStopMessage,
  MonitorOneshotMessage,
  ShellExecMessage,
  ClipboardGetMessage,
  ClipboardSetMessage,
  TransferCancelMessage,
  InspectAttachMessage,
  InspectDetachMessage,
  InspectDumpMessage,
  InspectFindMessage,
  AgentSubscribeMessage,
  AgentUnsubscribeMessage,
  AgentRunCancelMessage,
])
export type ClientMessage = z.infer<typeof ClientMessageSchema>
