import { z } from 'zod'
import type { RecordingDoc, RecordingStep, RecordingTarget } from '@enkaku/protocol'

/**
 * The compiler (plan 94 §4.7, §5 step 94.5) — turns a reviewed
 * `RecordingDoc` into the TWO kinds of generated source this plan's whole
 * design hangs on (§3.1's diagram): the THIN `defineRecording({...})` entry
 * that gets regenerated on every publish, and the EXPANDED plain
 * `defineScript({...})` entry `POST /api/recordings/:slug/detach` writes
 * once and never touches again. Both are pure functions of `doc` — no I/O,
 * no randomness, no wall clock — so publishing twice with no edit in
 * between writes byte-identical bytes (§4.7's own "a recompile that changes
 * nothing writes nothing").
 *
 * Neither function here executes anything (F18, F11): they produce TEXT,
 * which `packages/core/src/api/recordings.ts` then writes into the
 * workspace and hands to the SAME `buildScriptFromWorkspace` /
 * `ctx.scripts.publish` path an operator's own hand-authored script already
 * goes through.
 */

function isIdentifier(key: string): boolean {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key)
}

/**
 * A small, deliberately naive JS-literal printer — NOT a general serialiser.
 * Every value this file ever hands it comes straight off `RecordingDocSchema`
 * (already Zod-validated numbers/strings/booleans/plain objects/arrays), so
 * the only escaping that matters is a quote or backslash inside a recorded
 * string (a tapped button's text, a typed literal). Object keys print
 * unquoted when they are already valid identifiers (`x`, `y`, `atMs`, `id`,
 * …) to match this repo's own code style (00-overview §4: "no semicolons,
 * single quotes, two-space indent") — quoted otherwise.
 */
function jsLiteral(value: unknown): string {
  if (value === null || value === undefined) return 'null'
  if (typeof value === 'number' || typeof value === 'boolean') return String(value)
  if (typeof value === 'string') {
    return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n').replace(/\r/g, '\\r')}'`
  }
  if (Array.isArray(value)) return `[${value.map(jsLiteral).join(', ')}]`
  const entries = Object.entries(value as Record<string, unknown>)
  return `{ ${entries.map(([k, v]) => `${isIdentifier(k) ? k : jsLiteral(k)}: ${jsLiteral(v)}`).join(', ')} }`
}

/** §3.6's own composition rule, applied literally: the same clamp `defineRecording`'s interpreter (`@enkaku/sdk`) runs at replay. */
function effectiveGapMs(step: RecordingStep, doc: RecordingDoc): number {
  return Math.min(Math.round(step.gapMs * doc.speed), doc.maxGapMs)
}

/** Every distinct `{ param }` name referenced by a `text` step (§4.2) — mirrors `define-recording.ts`'s own `collectParamNames`, duplicated rather than imported because that function is not exported from the SDK's public surface (it is this file's own compiled OUTPUT that needs to agree with it, not a shared dependency). */
export function collectParamNames(doc: RecordingDoc): string[] {
  const names = new Set<string>()
  for (const step of doc.steps) {
    if (step.kind === 'text' && typeof step.value === 'object') names.add(step.value.param)
  }
  return [...names].sort()
}

/**
 * The compiled script's own declared parameter schema (plan 94 §4.2) — every
 * `{ param }` reference becomes one REQUIRED `z.string()` field, exactly as
 * `defineRecording` builds it at runtime. Returned as a real Zod schema so
 * both `emitRecordingEntry`'s reader (a human) and `POST
 * /:slug/publish` (which needs a JSON Schema for the `scripts.paramsSchema`
 * column, never executing the bundle to discover it — F11) can use it.
 */
export function paramsSchemaFor(doc: RecordingDoc): z.ZodTypeAny {
  const names = collectParamNames(doc)
  return z.object(Object.fromEntries(names.map((name) => [name, z.string()])))
}

/** The JSON Schema `publishScript`'s `paramsSchema` column stores — derived the same way `compileWorkflowParams` derives one for a workflow, without ever importing or executing the compiled bundle (F11). */
export function paramsJsonSchemaFor(doc: RecordingDoc): unknown {
  return z.toJSONSchema(paramsSchemaFor(doc))
}

/**
 * Emits the three-line generated entry from a recording document (plan 94
 * §3.1, §4.7). Deterministic: the same document always produces
 * byte-identical output, so a "recompile" that changes nothing writes
 * nothing — `recordings.test.ts`'s own idempotency test relies on this.
 */
export function emitRecordingEntry(doc: RecordingDoc): string {
  const json = JSON.stringify(doc, null, 2)
  return [
    `// GENERATED by Enkaku's recorder from /recordings/${doc.name}.recording.json.`,
    `// Edits here are overwritten on the next compile — use "Detach" to take ownership.`,
    `import { defineRecording } from '@enkaku/sdk'`,
    '',
    `export default defineRecording(${json})`,
    '',
  ].join('\n')
}

function dispatchLine(step: RecordingStep): string {
  switch (step.kind) {
    case 'tap': {
      const t: RecordingTarget = step.target
      if (t.kind === 'selector') return `await device.tap(${jsLiteral(t.selector)})`
      const opts = step.holdMs !== undefined ? `, { holdMs: ${step.holdMs} }` : ''
      return `await device.tapNorm(${jsLiteral(t.pos)}${opts})`
    }
    case 'longPress': {
      const t: RecordingTarget = step.target
      if (t.kind === 'selector') return `await device.longPress(${jsLiteral(t.selector)}, ${step.holdMs})`
      return `await device.tapNorm(${jsLiteral(t.pos)}, { holdMs: ${step.holdMs} })`
    }
    case 'gesture':
      return `await device.gesture(${jsLiteral(step.samples)})`
    case 'swipe':
      return `await device.swipeNorm(${jsLiteral(step.from)}, ${jsLiteral(step.to)}, ${step.durationMs})`
    case 'key':
      return `await device.key(${step.keycode})`
    case 'text':
      if (typeof step.value === 'string') return `await device.type(${jsLiteral(step.value)})`
      return `await device.type(ctx.params.${step.value.param})`
  }
}

/**
 * The Detach emitter (plan 94 §4.7, criterion 4) — a PLAIN `defineScript`
 * with every step expanded as a literal SDK call, not an interpreter loop
 * (F18: no orchestration lives in the SDK's authoring layer, and a large
 * generated file nobody will read fails F12 as surely as wrong code would).
 * Read top to bottom, this is exactly what a human who recorded the macro by
 * hand would have written — one `await` per action, in order, each preceded
 * by a comment naming its position and the sleep the interpreter would have
 * taken. The result belongs to the operator from the moment it is written:
 * nothing in this codebase ever regenerates a file at `/scripts/<slug>.ts`.
 */
export function emitDetachedScript(doc: RecordingDoc): string {
  const paramNames = collectParamNames(doc)
  const hasParams = paramNames.length > 0
  const hasLiteralText = doc.steps.some((s) => s.kind === 'text' && typeof s.value === 'string')

  const lines: string[] = []
  lines.push(`// GENERATED by Enkaku's recorder from /recordings/${doc.name}.recording.json, then detached.`)
  lines.push('// This file is now yours — Enkaku will not regenerate it.')
  if (hasLiteralText) {
    lines.push('// Contains at least one literal typed string, stored verbatim at the moment this was detached.')
  }
  lines.push("import { defineScript } from '@enkaku/sdk'")
  if (hasParams) lines.push("import { z } from 'zod'")
  lines.push('')
  lines.push('const sleep = (ms: number): Promise<void> => new Promise((resolve) => setTimeout(resolve, ms))')
  lines.push('')
  lines.push('export default defineScript({')
  lines.push(`  id: ${jsLiteral(doc.name)},`)
  lines.push(`  version: ${jsLiteral(doc.version)},`)
  lines.push(`  params: ${hasParams ? `z.object({ ${paramNames.map((n) => `${n}: z.string()`).join(', ')} })` : 'z.object({})'},`)
  lines.push(`  reset: { packages: ${jsLiteral(doc.packages)} },`)
  lines.push('  timing: { betweenActionMs: [0, 0] },')
  lines.push('  async run(ctx) {')
  lines.push('    const device = ctx.device')
  doc.steps.forEach((step, i) => {
    const gap = effectiveGapMs(step, doc)
    lines.push(`    // step ${i + 1}/${doc.steps.length}: ${step.kind}`)
    if (gap > 0) lines.push(`    await sleep(${gap})`)
    lines.push(`    ${dispatchLine(step)}`)
  })
  lines.push('  },')
  if (doc.cleanup === 'force-stop' && doc.packages.length > 0) {
    lines.push('  async finish(ctx) {')
    for (const pkg of doc.packages) {
      lines.push(`    await ctx.device.app.forceStop(${jsLiteral(pkg)})`)
    }
    lines.push('  },')
  }
  lines.push('})')
  lines.push('')
  return lines.join('\n')
}
