/**
 * Generate the release entrypoint for `bun build --compile`.
 *
 * It statically imports every file of the Studio static export and every
 * drizzle migration with `with { type: 'file' }` (so Bun embeds them into the
 * binary), registers the path maps in enkaku-core's embedded-assets registry,
 * and only then boots the normal core entrypoint.
 *
 * Output: packages/core/src/entry-release.gen.ts (gitignored).
 * Usage:  bun scripts/gen-embedded-entry.ts   (after `bun run build:studio`)
 */
import { readdirSync, statSync, writeFileSync } from 'node:fs'
import { join, relative } from 'node:path'

const root = join(import.meta.dir, '..')
const studioOut = join(root, 'packages', 'studio', 'out')
const drizzleDir = join(root, 'packages', 'core', 'drizzle')
const outFile = join(root, 'packages', 'core', 'src', 'entry-release.gen.ts')

function walk(dir: string): string[] {
  const files: string[] = []
  for (const name of readdirSync(dir)) {
    const full = join(dir, name)
    if (statSync(full).isDirectory()) files.push(...walk(full))
    else files.push(full)
  }
  return files.sort()
}

function assertExists(dir: string, hint: string): void {
  try {
    statSync(dir)
  } catch {
    console.error(`missing ${dir} — ${hint}`)
    process.exit(1)
  }
}

assertExists(join(studioOut, 'index.html'), 'run `bun run build:studio` first')
assertExists(drizzleDir, 'drizzle migrations folder not found')

// Snapshots are drizzle-kit's input for generating the NEXT migration; the
// runtime migrator only needs the journal and the .sql files.
const studio = walk(studioOut).map((f) => relative(studioOut, f))
const drizzle = walk(drizzleDir)
  .map((f) => relative(drizzleDir, f))
  .filter((rel) => rel.endsWith('.sql') || rel === join('meta', '_journal.json'))

const toPosix = (p: string) => p.split('\\').join('/')
const lines: string[] = [
  '// GENERATED by scripts/gen-embedded-entry.ts — do not edit, do not commit.',
  "import { registerEmbeddedAssets } from './embedded'",
]
const entries: { map: 'studio' | 'drizzle'; rel: string; ident: string }[] = []

let i = 0
for (const rel of studio) {
  const ident = `s${i++}`
  lines.push(`import ${ident} from '../../studio/out/${toPosix(rel)}' with { type: 'file' }`)
  entries.push({ map: 'studio', rel: toPosix(rel), ident })
}
for (const rel of drizzle) {
  const ident = `d${i++}`
  lines.push(`import ${ident} from '../drizzle/${toPosix(rel)}' with { type: 'file' }`)
  entries.push({ map: 'drizzle', rel: toPosix(rel), ident })
}

lines.push('', 'registerEmbeddedAssets({')
for (const map of ['studio', 'drizzle'] as const) {
  lines.push(`  ${map}: {`)
  for (const e of entries) if (e.map === map) lines.push(`    ${JSON.stringify(e.rel)}: ${e.ident},`)
  lines.push('  },')
}
lines.push('})', '', "await import('./index')", '')

writeFileSync(outFile, lines.join('\n'))
console.log(`generated ${relative(root, outFile)} (${studio.length} studio files, ${drizzle.length} drizzle files)`)
