import { statSync, mkdirSync } from 'node:fs'
import { join } from 'node:path'
import { eq } from 'drizzle-orm'
import {
  pullFile,
  pushFile,
  shellQuote,
  statRemote,
  type AdbExecOptions,
  type AdbStreamHandle,
  type AdbStreamOptions,
  type RawStream,
  type ShellResult,
} from '@enkaku/adb'
import { grantRuntimePermissions, isGrantAllPermissionsRejection } from '@enkaku/drivers'
import type {
  DeviceMediaKind,
  DeviceMediaListArgs,
  DeviceMediaListResult,
  InstallResult,
  MediaScanMode,
  MediaScanResult,
  PushResult,
} from '@enkaku/protocol'
import type { Db } from '../db'
import { artifacts, devices } from '../db/schema'
import { devicePullArtifactPath, registerDeviceArtifact } from '../runner/artifact-store'
import { EnkakuError } from '../util/errors'
import { findMediaIdForPath, queryDeviceMedia, type MediaQueryBackend } from './media-query'
import { validateRemotePath } from './path-validate'

/**
 * File transfer and APK install (plan 39 §4.2) — push, pull, and install all
 * run on the streaming lane (`AdbBackend.openRaw`/`execStream`), NEVER
 * `PerDeviceQueue`: a 60 MB push must not block video, input, or jobs on
 * that device (plan 24 §3.1, plan 39 §3.3, acceptance #2).
 *
 * Scoped to LOCAL devices only. Plan 39 depends on plans 22.1/24/27 — never
 * 25/28, which establish cloud parity — and every acceptance criterion and
 * manual smoke test in the plan targets a device reachable through the
 * local `AdbClient`. A node-owned device refuses with a clear, coded
 * error rather than silently degrading; extending this to the cloud tunnel
 * (mirroring `adb-endpoint.ts`'s local/remote split) is recorded as an open
 * question rather than built speculatively and left untested.
 */

/** The slice of `AdbClient` this module actually needs — kept as a narrow
 * structural interface (not the concrete class) so a unit test can supply a
 * lightweight fake without satisfying every private member `AdbClient` has. */
export interface AdbBackend {
  openRaw(serial: string, service: string): Promise<RawStream>
  exec(serial: string, cmd: string, opts?: AdbExecOptions): Promise<ShellResult>
  execStream(serial: string, cmd: string, opts: AdbStreamOptions): Promise<AdbStreamHandle>
}

export interface TransferOpts {
  /** Correlates `transfer.progress` broadcasts and `cancel()` — generated by the caller (an API route, the `internal:install` executor, or the script IPC bridge) before starting. */
  transferId: string
  onProgress?(sent: number, total: number | null): void
  /**
   * The run that started this transfer, if any (plan 93 §3.13, §4.6, step
   * 93.9 — closes F12; re-keyed from `jobId` to `runId` by plan 211 §3.2
   * decision 9, matching `artifacts.run_id`). Only `pull` uses it,
   * forwarding it into `registerDeviceArtifact` so a bulk pull's artifacts
   * are traceable back to the batch/run that produced them. Optional and
   * undefined for the REST route and the script IPC bridge, exactly like
   * before this field existed — only the `internal:pull` executor threads
   * its own `ctx.runId`.
   */
  runId?: string | null
}

/** `push`'s extra opt (plan 90 §4.6) — `'auto'` (the default) scans only
 * when the resolved remote path sits under a known media root. */
export interface PushOpts extends TransferOpts {
  mediaScan?: MediaScanMode
}

export interface InstallOpts {
  /** `-r`, default true. */
  reinstall?: boolean
  /** `-g`, default true. */
  grantPermissions?: boolean
  /** `-d`, default false. */
  allowDowngrade?: boolean
  /**
   * The package this APK installs, when the caller knows it. Only used on the
   * `-g`-refused fallback path (see `performInstall`): the explicit
   * `pm grant`s that stand in for the flag have to be aimed at a package
   * name, and `pm install` does not reliably print one. A caller that cannot
   * supply it (an operator installing an arbitrary uploaded APK) still gets
   * the install — with a line in `output` saying the runtime permissions were
   * left ungranted, rather than a silent half-install.
   */
  packageName?: string
}

export interface TransferService {
  push(deviceId: string, artifactId: string, remotePath: string, opts: PushOpts): Promise<PushResult>
  pull(deviceId: string, remotePath: string, opts: TransferOpts): Promise<{ artifactId: string; bytes: number }>
  install(deviceId: string, artifactId: string, opts: InstallOpts & TransferOpts): Promise<InstallResult>
  /**
   * Plan 106 §5 step 106.8 (§9 Q5's recommendation, now built) — installs an
   * APK already resolved to an absolute LOCAL path, never a row in the
   * `artifacts` table. Device-preparation components (`ui-server-component.ts`)
   * resolve their own APK from the Toolchain Manager / `ENKAKU_GUEST_AGENT_PATH`
   * (G7's three-tier rule) — routing that path through `resolveArtifact`
   * would mean fabricating a hidden `artifacts` row for a file the operator
   * never uploaded and would never expect to see in the artifact browser.
   * Otherwise IDENTICAL machinery to `install()` below — the SAME
   * push-with-onProgress, `pm install -r -g`, parsed-failure-text, and
   * cleanup-on-every-exit-path (`performInstall`, shared by both) — so a
   * preparation install gets the exact same real byte progress and staged-file
   * cleanup guarantee an operator's own install already has.
   */
  installFromLocalApk(deviceId: string, absPath: string, opts: InstallOpts & TransferOpts): Promise<InstallResult>
  /** Idempotent — cancelling an unknown or already-finished transferId is a no-op. */
  cancel(transferId: string): void
  /**
   * What MediaStore holds on the device, newest first — the READ counterpart
   * to `push`'s `mediaScan`. Lives on this port because MediaStore is a view
   * of the same on-device files push and pull already move; it moves no bytes
   * and takes no `transferId`, so it never enters the transfer registry.
   */
  listMedia(deviceId: string, args: DeviceMediaListArgs): Promise<DeviceMediaListResult>
}

export interface TransferServiceDeps {
  db: Db
  dataDir: string
  adb: () => AdbBackend | null
  /** True for a node-owned device (plan 39 §9 open question — cloud is out of scope for this plan). */
  isRemote?: (deviceId: string) => boolean
  settings: () => { maxPushBytes: number; maxPullBytes: number; installTimeoutMs: number }
}

function concatChunks(chunks: Uint8Array[]): Uint8Array {
  const total = chunks.reduce((n, c) => n + c.length, 0)
  const out = new Uint8Array(total)
  let offset = 0
  for (const c of chunks) {
    out.set(c, offset)
    offset += c.length
  }
  return out
}

interface Backend {
  serial: string
  adb: AdbBackend
}

function resolveBackend(deps: TransferServiceDeps, deviceId: string): Backend {
  if (deps.isRemote?.(deviceId)) {
    throw new EnkakuError('E_UNSUPPORTED', 'file transfer is only available for local devices in this release')
  }
  const row = deps.db.select().from(devices).where(eq(devices.id, deviceId)).get()
  if (!row) throw new EnkakuError('device_not_found', `no such device: ${deviceId}`)
  const adb = deps.adb()
  if (!adb) throw new EnkakuError('E_ADB_UNAVAILABLE', 'the adb subsystem is not ready')
  return { serial: row.serial, adb }
}

interface ResolvedArtifact {
  abs: string
  path: string
  sizeBytes: number
}

/** Server-side artifact resolution (plan 39 §3.5, acceptance #8): the ONLY way a source reaches `pushFile`/`pm install` — never a client-named URL or filesystem path. */
async function resolveArtifact(deps: TransferServiceDeps, artifactId: string): Promise<ResolvedArtifact> {
  const row = deps.db.select().from(artifacts).where(eq(artifacts.id, artifactId)).get()
  if (!row) throw new EnkakuError('artifact_not_found', `no such artifact: ${artifactId}`)
  const abs = join(deps.dataDir, row.path)
  let sizeBytes: number
  try {
    sizeBytes = statSync(abs).size
  } catch {
    throw new EnkakuError('artifact_not_found', 'the artifact file is no longer on disk')
  }
  return { abs, path: row.path, sizeBytes }
}

/** Runs a lane-shaped shell command to completion and returns its combined output — `pm install`'s home (plan 39 §3.4): the lane, never a new huge `exec` timeout. */
function runOnLane(backend: Backend, cmd: string, timeoutMs: number, signal: AbortSignal): Promise<string> {
  return new Promise((resolve, reject) => {
    const chunks: Uint8Array[] = []
    backend.adb
      .execStream(backend.serial, cmd, {
        onData: (chunk) => chunks.push(chunk),
        onEnd: (reason) => {
          const text = new TextDecoder().decode(concatChunks(chunks))
          if (reason === 'closed') resolve(text)
          else if (reason === 'stopped') reject(new EnkakuError('E_TRANSFER_CANCELLED', 'the install was cancelled'))
          else reject(new EnkakuError('E_INSTALL_TIMEOUT', `pm install ended unexpectedly (${reason})`))
        },
        absoluteTimeoutMs: timeoutMs,
        signal,
      })
      .catch(reject)
  })
}

/** `pm install`'s two possible endings: `Success` or `Failure [REASON]` (plan 39 acceptance #3 — the parsed reason, not a generic error). */
function parseInstallOutput(output: string): { success: true; pkg: string | null } | { success: false; reason: string } {
  const trimmed = output.trim()
  const failMatch = trimmed.match(/Failure\s*\[([^\]]*)\]/)
  if (failMatch) return { success: false, reason: failMatch[1] || 'unknown' }
  if (/^Success/m.test(trimmed)) {
    // Rarely present on modern `pm`, but some OEM builds echo it — never guessed otherwise (plan 39 §4.2 step 5).
    const pkgMatch = trimmed.match(/Success:\s*(\S+)/)
    return { success: true, pkg: pkgMatch?.[1] ?? null }
  }
  return { success: false, reason: trimmed || 'pm install produced no recognisable output' }
}

/**
 * `mediaScan` (plan 90 §3.4, §4.6) — the one genuinely missing step for
 * "gallery" as a farm operator experiences it: `push` already lands bytes
 * anywhere (F29), and the shell can write under any of these roots freely
 * (scoped storage restricts apps, not the shell, F31) — MediaStore is the
 * only thing that never learns about the file (F30). Both spellings of the
 * external volume are listed because OEM builds and API levels disagree on
 * which one a caller/app actually sees.
 */
const MEDIA_ROOTS = [
  '/sdcard/DCIM',
  '/sdcard/Pictures',
  '/sdcard/Movies',
  '/sdcard/Music',
  '/sdcard/Download',
  '/storage/emulated/0/DCIM',
  '/storage/emulated/0/Pictures',
  '/storage/emulated/0/Movies',
  '/storage/emulated/0/Music',
  '/storage/emulated/0/Download',
]

function isMediaPath(path: string): boolean {
  return MEDIA_ROOTS.some((root) => path === root || path.startsWith(`${root}/`))
}

/**
 * `content call --method scan_file` then `scan_volume` (H3, plan 90 §4.6) —
 * the first to exit 0 wins. Never throws: a failed scan is reported in the
 * result and never fails the push, because the bytes already landed either
 * way (§3.4). This is also how H3 — "does `scan_file` work as the shell
 * user on Android 10+" — gets settled in the field: the method that
 * actually answered is named in the result, not assumed in a comment.
 */
async function runMediaScan(backend: Backend, remotePath: string): Promise<MediaScanResult> {
  const startedAt = Date.now()
  const attempt = (cmd: string): Promise<ShellResult | null> =>
    backend.adb.exec(backend.serial, cmd, { profile: 'appLifecycle' }).catch(() => null)

  /**
   * The `_id` MediaStore now holds for this exact path. Never allowed to fail
   * the scan it annotates: the scan itself already succeeded, and a lookup
   * that could not answer is reported as `mediaId: null` — "unknown" — rather
   * than downgrading a scan that genuinely ran.
   */
  const lookupId = async (): Promise<string | null> => {
    const kind = mediaKindForPath(remotePath)
    if (kind === null) return null
    return findMediaIdForPath(mediaQueryBackend(backend), kind, remotePath).catch(() => null)
  }

  const scanFileCmd = `content call --uri content://media --method scan_file --arg ${shellQuote(remotePath)}`
  const scanFile = await attempt(scanFileCmd)
  if (scanFile && scanFile.exitCode === 0) {
    return { ran: true, method: 'scan_file', ms: Date.now() - startedAt, mediaId: await lookupId() }
  }

  const scanVolumeCmd = 'content call --uri content://media --method scan_volume --arg external_primary'
  const scanVolume = await attempt(scanVolumeCmd)
  if (scanVolume && scanVolume.exitCode === 0) {
    return { ran: true, method: 'scan_volume', ms: Date.now() - startedAt, mediaId: await lookupId() }
  }

  // Both failed — degrade visibly rather than silently claiming success.
  // `scan_file`'s own failure is worth naming too, since it is the one
  // OEMs/API levels most often disagree on (H3).
  const parts: string[] = []
  parts.push(scanFile ? `scan_file exited ${scanFile.exitCode ?? 'unknown'}` : 'scan_file threw')
  parts.push(scanVolume ? `scan_volume exited ${scanVolume.exitCode ?? 'unknown'}` : 'scan_volume threw')
  return { ran: false, method: null, ms: Date.now() - startedAt, error: parts.join('; '), mediaId: null }
}

/**
 * MediaStore keeps three separate volumes, so reading a row back means knowing
 * which one to ask. Decided from the file EXTENSION, which is the only thing
 * known host-side without another round trip — and the extension is what
 * `post-video.ts` already preserves precisely so a container and its name
 * agree.
 *
 * Null for anything not obviously media (an APK, a log, a `.bin`): no volume
 * would hold it, and asking anyway would cost a shell round trip to learn
 * nothing. A caller reads null as "not a media file", never as a failure.
 */
function mediaKindForPath(remotePath: string): DeviceMediaKind | null {
  const ext = remotePath.split('/').pop()?.split('.').pop()?.toLowerCase() ?? ''
  if (['mp4', 'mov', 'm4v', 'webm', 'mkv', '3gp', 'avi'].includes(ext)) return 'video'
  if (['jpg', 'jpeg', 'png', 'gif', 'webp', 'heic', 'heif', 'bmp'].includes(ext)) return 'image'
  if (['mp3', 'm4a', 'aac', 'wav', 'ogg', 'flac', 'opus'].includes(ext)) return 'audio'
  return null
}

/** Adapts the adb backend to `media-query.ts`'s narrow port — one `exec`, never throwing. */
function mediaQueryBackend(backend: Backend): MediaQueryBackend {
  return {
    exec: (cmd) =>
      backend.adb
        .exec(backend.serial, cmd, { profile: 'appLifecycle' })
        .then((r) => ({ exitCode: r.exitCode, stdout: r.stdout }))
        .catch(() => null),
  }
}

interface LocalApk {
  abs: string
  sizeBytes: number
}

/**
 * Shared by `install()` (artifact-table-resolved) and `installFromLocalApk()`
 * (a caller-resolved absolute path, plan 106 §5 step 106.8) — push the bytes
 * with real progress, run `pm install`, parse its output for a `Failure
 * [REASON]` line REGARDLESS of `pm`'s own exit code (`runOnLane` resolves on
 * stream close, never branches on an exit status — `pm install` can exit 0
 * while printing `Failure [...]`, and this function would otherwise record a
 * success that never installed), and delete the staged file in a `finally`
 * on every exit path: success, a parsed `pm install` failure, a cancel, or
 * `pushFile` itself throwing.
 */
async function performInstall(
  deps: TransferServiceDeps,
  backend: Backend,
  controller: AbortController,
  local: LocalApk,
  opts: InstallOpts & TransferOpts,
): Promise<InstallResult> {
  const remotePath = `/data/local/tmp/enkaku-${crypto.randomUUID()}.apk`
  const startedAt = Date.now()
  try {
    const stream = await backend.adb.openRaw(backend.serial, 'sync:')
    try {
      await pushFile(stream, {
        localPath: local.abs,
        remotePath,
        onProgress: opts.onProgress ? (sent, total) => opts.onProgress?.(sent, total) : undefined,
        signal: controller.signal,
      })
      stream.close()
    } catch (err) {
      stream.close(true)
      throw err
    }

    // `-r` (reinstall) and `-g` (auto-grant runtime permissions) both default
    // true — the flags `hostAdb(['install', '-r', '-g', ...])` always passed
    // before this move. Dropping `-r` would fail a reinstall of an existing
    // version; dropping `-g` would leave runtime permissions ungranted,
    // which breaks a consumer (e.g. the UI server) at USE time, not install
    // time (plan 106 §5 step 106.8) — asserted directly in `transfer.test.ts`.
    const runInstall = async (grant: boolean): Promise<string> => {
      const flags = [(opts.reinstall ?? true) ? '-r' : '', grant ? '-g' : '', opts.allowDowngrade ? '-d' : ''].filter(Boolean).join(' ')
      const cmd = `pm install ${flags} ${shellQuote(remotePath)}`.replace(/\s+/g, ' ').trim()
      return runOnLane(backend, cmd, deps.settings().installTimeoutMs, controller.signal)
    }

    const wantGrant = opts.grantPermissions ?? true
    let output = await runInstall(wantGrant)
    let parsed = parseInstallOutput(output)
    let grantNote = ''

    // Some builds refuse the `-g` flag itself rather than the install: a
    // Xiaomi 25128PC17G (HyperOS, Android 16) denies it to the shell user, and
    // that single rejection was failing BOTH ui-server APKs and the guest
    // agent on that phone. `-g` is a convenience — install without it and
    // grant the same permissions by hand. Detected on the exact rejection, so
    // an ordinary `Failure [INSTALL_FAILED_*]` is still a failure and is
    // never retried blindly (see `isGrantAllPermissionsRejection`).
    if (!parsed.success && wantGrant && isGrantAllPermissionsRejection(parsed.reason)) {
      output = await runInstall(false)
      parsed = parseInstallOutput(output)
      if (parsed.success) {
        const packageName = opts.packageName ?? parsed.pkg
        if (packageName) {
          // Throws when a grant does not take — an app installed WITHOUT the
          // permissions it asked for is a worse state than one that failed to
          // install, and must not be reported as a success.
          await grantRuntimePermissions({
            exec: (cmd) => backend.adb.exec(backend.serial, cmd, { profile: 'appLifecycle' }),
            packageName,
          })
          grantNote = `\n[enkaku] this device refuses the -g install flag; ${packageName}'s runtime permissions were granted explicitly instead`
        } else {
          // Named in the result rather than dropped: the caller asked for
          // `-g`, did not get it, and nothing here knows which package to
          // aim `pm grant` at.
          grantNote =
            '\n[enkaku] this device refuses the -g install flag and no package name was supplied, so runtime permissions were NOT granted — the app may misbehave at use time'
        }
      }
    }

    if (!parsed.success) {
      throw new EnkakuError('E_INSTALL_FAILED', parsed.reason)
    }
    return { package: opts.packageName ?? parsed.pkg, durationMs: Date.now() - startedAt, output: `${output.trim()}${grantNote}` }
  } finally {
    // The staged APK is deleted in this `finally` on every exit path —
    // success, failure, AND cancel (plan 39 §4.2 step 4, acceptance #4).
    // Best-effort: a device that already lost its connection cannot
    // usefully surface a second error here.
    await backend.adb.exec(backend.serial, `rm -f ${shellQuote(remotePath)}`, { profile: 'appLifecycle' }).catch(() => {})
  }
}

export function createTransferService(deps: TransferServiceDeps): TransferService {
  const controllers = new Map<string, AbortController>()

  function begin(transferId: string): AbortController {
    const controller = new AbortController()
    controllers.set(transferId, controller)
    return controller
  }

  function end(transferId: string): void {
    controllers.delete(transferId)
  }

  return {
    cancel(transferId) {
      controllers.get(transferId)?.abort()
    },

    listMedia(deviceId, args) {
      // No `begin`/`end`: this is a shell read, not a byte transfer, so it
      // must never appear in `GET /api/transfers` beside a running push.
      return queryDeviceMedia(mediaQueryBackend(resolveBackend(deps, deviceId)), args)
    },

    async push(deviceId, artifactId, remotePath, opts) {
      const path = validateRemotePath(remotePath)
      const artifact = await resolveArtifact(deps, artifactId)
      const maxPushBytes = deps.settings().maxPushBytes
      if (artifact.sizeBytes > maxPushBytes) {
        throw new EnkakuError('E_TRANSFER_TOO_LARGE', `the artifact is ${artifact.sizeBytes} bytes, exceeding the ${maxPushBytes}-byte push limit`)
      }
      const backend = resolveBackend(deps, deviceId)
      const controller = begin(opts.transferId)
      try {
        const stream = await backend.adb.openRaw(backend.serial, 'sync:')
        try {
          await pushFile(stream, {
            localPath: artifact.abs,
            remotePath: path,
            onProgress: opts.onProgress ? (sent, total) => opts.onProgress?.(sent, total) : undefined,
            signal: controller.signal,
          })
          stream.close()
        } catch (err) {
          stream.close(true)
          throw err
        }
        // §4.6: `auto` (the default) scans only under a known media root;
        // `always`/`never` override the detection. The bytes are already on
        // the device by this point regardless of what happens next.
        const mode = opts.mediaScan ?? 'auto'
        const shouldScan = mode === 'always' || (mode === 'auto' && isMediaPath(path))
        const mediaScan: MediaScanResult = shouldScan ? await runMediaScan(backend, path) : { ran: false, method: null, ms: 0, mediaId: null }
        return { mediaScan }
      } finally {
        end(opts.transferId)
      }
    },

    async pull(deviceId, remotePath, opts) {
      const path = validateRemotePath(remotePath)
      const maxPullBytes = deps.settings().maxPullBytes
      const backend = resolveBackend(deps, deviceId)
      const controller = begin(opts.transferId)
      try {
        const stream = await backend.adb.openRaw(backend.serial, 'sync:')
        try {
          // Enforcement #1 (plan 39 §3.6): refuse before any bytes move.
          const stat = await statRemote(stream, path)
          if (!stat) throw new EnkakuError('E_NOT_FOUND', `remote path does not exist: ${path}`)
          if (stat.size > maxPullBytes) {
            throw new EnkakuError('E_TRANSFER_TOO_LARGE', `the remote file is ${stat.size} bytes, exceeding the ${maxPullBytes}-byte pull limit`)
          }
          const label = path.split('/').pop() || 'pulled-file'
          const ext = label.includes('.') ? (label.split('.').pop() as string) : 'bin'
          const dest = devicePullArtifactPath(deps.dataDir, deviceId, label, ext)
          mkdirSync(dest.dir, { recursive: true })
          // Enforcement #2 (plan 39 §3.6): the running total is also checked
          // WHILE streaming, inside `pullFile` itself, so a file that grows
          // between the `stat` above and now still cannot exceed the cap.
          const { bytes } = await pullFile(stream, {
            remotePath: path,
            localPath: dest.abs,
            maxBytes: maxPullBytes,
            onProgress: opts.onProgress ? (received) => opts.onProgress?.(received, stat.size) : undefined,
            signal: controller.signal,
          })
          stream.close()
          const info = registerDeviceArtifact({ db: deps.db }, { deviceId, label, relPath: dest.rel, sizeBytes: bytes, runId: opts.runId ?? null })
          return { artifactId: info.id, bytes }
        } catch (err) {
          stream.close(true)
          throw err
        }
      } finally {
        end(opts.transferId)
      }
    },

    async install(deviceId, artifactId, opts) {
      const artifact = await resolveArtifact(deps, artifactId)
      if (!/\.apk$/i.test(artifact.path)) {
        throw new EnkakuError('E_BAD_REQUEST', 'the artifact is not an .apk file')
      }
      const maxPushBytes = deps.settings().maxPushBytes
      if (artifact.sizeBytes > maxPushBytes) {
        throw new EnkakuError('E_TRANSFER_TOO_LARGE', `the artifact is ${artifact.sizeBytes} bytes, exceeding the ${maxPushBytes}-byte push limit`)
      }
      const backend = resolveBackend(deps, deviceId)
      const controller = begin(opts.transferId)
      try {
        return await performInstall(deps, backend, controller, { abs: artifact.abs, sizeBytes: artifact.sizeBytes }, opts)
      } finally {
        end(opts.transferId)
      }
    },

    async installFromLocalApk(deviceId, absPath, opts) {
      let sizeBytes: number
      try {
        sizeBytes = statSync(absPath).size
      } catch {
        throw new EnkakuError('E_NOT_FOUND', `the apk is no longer on disk: ${absPath}`)
      }
      const maxPushBytes = deps.settings().maxPushBytes
      if (sizeBytes > maxPushBytes) {
        throw new EnkakuError('E_TRANSFER_TOO_LARGE', `the apk is ${sizeBytes} bytes, exceeding the ${maxPushBytes}-byte push limit`)
      }
      const backend = resolveBackend(deps, deviceId)
      const controller = begin(opts.transferId)
      try {
        return await performInstall(deps, backend, controller, { abs: absPath, sizeBytes }, opts)
      } finally {
        end(opts.transferId)
      }
    },
  }
}
