import { statSync, mkdirSync } from 'node:fs'
import { join } from 'node:path'
import { eq } from 'drizzle-orm'
import {
  pullFile,
  pushFile,
  shellQuote,
  statRemote,
  type AdbExecOptions,
  type AdbStreamHandle,
  type AdbStreamOptions,
  type RawStream,
  type ShellResult,
} from '@enkaku/adb'
import type { InstallResult } from '@enkaku/protocol'
import type { Db } from '../db'
import { artifacts, devices } from '../db/schema'
import { devicePullArtifactPath, registerDeviceArtifact } from '../runner/artifact-store'
import { EnkakuError } from '../util/errors'
import { validateRemotePath } from './path-validate'

/**
 * File transfer and APK install (plan 39 §4.2) — push, pull, and install all
 * run on the streaming lane (`AdbBackend.openRaw`/`execStream`), NEVER
 * `PerDeviceQueue`: a 60 MB push must not block video, input, or jobs on
 * that device (plan 24 §3.1, plan 39 §3.3, acceptance #2).
 *
 * Scoped to LOCAL devices only. Plan 39 depends on plans 22.1/24/27 — never
 * 25/28, which establish cloud parity — and every acceptance criterion and
 * manual smoke test in the plan targets a device reachable through the
 * local `AdbClient`. A node-owned device refuses with a clear, coded
 * error rather than silently degrading; extending this to the cloud tunnel
 * (mirroring `adb-endpoint.ts`'s local/remote split) is recorded as an open
 * question rather than built speculatively and left untested.
 */

/** The slice of `AdbClient` this module actually needs — kept as a narrow
 * structural interface (not the concrete class) so a unit test can supply a
 * lightweight fake without satisfying every private member `AdbClient` has. */
export interface AdbBackend {
  openRaw(serial: string, service: string): Promise<RawStream>
  exec(serial: string, cmd: string, opts?: AdbExecOptions): Promise<ShellResult>
  execStream(serial: string, cmd: string, opts: AdbStreamOptions): Promise<AdbStreamHandle>
}

export interface TransferOpts {
  /** Correlates `transfer.progress` broadcasts and `cancel()` — generated by the caller (an API route, the `internal:install` executor, or the script IPC bridge) before starting. */
  transferId: string
  onProgress?(sent: number, total: number | null): void
}

export interface InstallOpts {
  /** `-r`, default true. */
  reinstall?: boolean
  /** `-g`, default true. */
  grantPermissions?: boolean
  /** `-d`, default false. */
  allowDowngrade?: boolean
}

export interface TransferService {
  push(deviceId: string, artifactId: string, remotePath: string, opts: TransferOpts): Promise<void>
  pull(deviceId: string, remotePath: string, opts: TransferOpts): Promise<{ artifactId: string; bytes: number }>
  install(deviceId: string, artifactId: string, opts: InstallOpts & TransferOpts): Promise<InstallResult>
  /** Idempotent — cancelling an unknown or already-finished transferId is a no-op. */
  cancel(transferId: string): void
}

export interface TransferServiceDeps {
  db: Db
  dataDir: string
  adb: () => AdbBackend | null
  /** True for a node-owned device (plan 39 §9 open question — cloud is out of scope for this plan). */
  isRemote?: (deviceId: string) => boolean
  settings: () => { maxPushBytes: number; maxPullBytes: number; installTimeoutMs: number }
}

function concatChunks(chunks: Uint8Array[]): Uint8Array {
  const total = chunks.reduce((n, c) => n + c.length, 0)
  const out = new Uint8Array(total)
  let offset = 0
  for (const c of chunks) {
    out.set(c, offset)
    offset += c.length
  }
  return out
}

interface Backend {
  serial: string
  adb: AdbBackend
}

function resolveBackend(deps: TransferServiceDeps, deviceId: string): Backend {
  if (deps.isRemote?.(deviceId)) {
    throw new EnkakuError('E_UNSUPPORTED', 'file transfer is only available for local devices in this release')
  }
  const row = deps.db.select().from(devices).where(eq(devices.id, deviceId)).get()
  if (!row) throw new EnkakuError('device_not_found', `no such device: ${deviceId}`)
  const adb = deps.adb()
  if (!adb) throw new EnkakuError('E_ADB_UNAVAILABLE', 'the adb subsystem is not ready')
  return { serial: row.serial, adb }
}

interface ResolvedArtifact {
  abs: string
  path: string
  sizeBytes: number
}

/** Server-side artifact resolution (plan 39 §3.5, acceptance #8): the ONLY way a source reaches `pushFile`/`pm install` — never a client-named URL or filesystem path. */
async function resolveArtifact(deps: TransferServiceDeps, artifactId: string): Promise<ResolvedArtifact> {
  const row = deps.db.select().from(artifacts).where(eq(artifacts.id, artifactId)).get()
  if (!row) throw new EnkakuError('artifact_not_found', `no such artifact: ${artifactId}`)
  const abs = join(deps.dataDir, row.path)
  let sizeBytes: number
  try {
    sizeBytes = statSync(abs).size
  } catch {
    throw new EnkakuError('artifact_not_found', 'the artifact file is no longer on disk')
  }
  return { abs, path: row.path, sizeBytes }
}

/** Runs a lane-shaped shell command to completion and returns its combined output — `pm install`'s home (plan 39 §3.4): the lane, never a new huge `exec` timeout. */
function runOnLane(backend: Backend, cmd: string, timeoutMs: number, signal: AbortSignal): Promise<string> {
  return new Promise((resolve, reject) => {
    const chunks: Uint8Array[] = []
    backend.adb
      .execStream(backend.serial, cmd, {
        onData: (chunk) => chunks.push(chunk),
        onEnd: (reason) => {
          const text = new TextDecoder().decode(concatChunks(chunks))
          if (reason === 'closed') resolve(text)
          else if (reason === 'stopped') reject(new EnkakuError('E_TRANSFER_CANCELLED', 'the install was cancelled'))
          else reject(new EnkakuError('E_INSTALL_TIMEOUT', `pm install ended unexpectedly (${reason})`))
        },
        absoluteTimeoutMs: timeoutMs,
        signal,
      })
      .catch(reject)
  })
}

/** `pm install`'s two possible endings: `Success` or `Failure [REASON]` (plan 39 acceptance #3 — the parsed reason, not a generic error). */
function parseInstallOutput(output: string): { success: true; pkg: string | null } | { success: false; reason: string } {
  const trimmed = output.trim()
  const failMatch = trimmed.match(/Failure\s*\[([^\]]*)\]/)
  if (failMatch) return { success: false, reason: failMatch[1] || 'unknown' }
  if (/^Success/m.test(trimmed)) {
    // Rarely present on modern `pm`, but some OEM builds echo it — never guessed otherwise (plan 39 §4.2 step 5).
    const pkgMatch = trimmed.match(/Success:\s*(\S+)/)
    return { success: true, pkg: pkgMatch?.[1] ?? null }
  }
  return { success: false, reason: trimmed || 'pm install produced no recognisable output' }
}

export function createTransferService(deps: TransferServiceDeps): TransferService {
  const controllers = new Map<string, AbortController>()

  function begin(transferId: string): AbortController {
    const controller = new AbortController()
    controllers.set(transferId, controller)
    return controller
  }

  function end(transferId: string): void {
    controllers.delete(transferId)
  }

  return {
    cancel(transferId) {
      controllers.get(transferId)?.abort()
    },

    async push(deviceId, artifactId, remotePath, opts) {
      const path = validateRemotePath(remotePath)
      const artifact = await resolveArtifact(deps, artifactId)
      const maxPushBytes = deps.settings().maxPushBytes
      if (artifact.sizeBytes > maxPushBytes) {
        throw new EnkakuError('E_TRANSFER_TOO_LARGE', `the artifact is ${artifact.sizeBytes} bytes, exceeding the ${maxPushBytes}-byte push limit`)
      }
      const backend = resolveBackend(deps, deviceId)
      const controller = begin(opts.transferId)
      try {
        const stream = await backend.adb.openRaw(backend.serial, 'sync:')
        try {
          await pushFile(stream, {
            localPath: artifact.abs,
            remotePath: path,
            onProgress: opts.onProgress ? (sent, total) => opts.onProgress?.(sent, total) : undefined,
            signal: controller.signal,
          })
          stream.close()
        } catch (err) {
          stream.close(true)
          throw err
        }
      } finally {
        end(opts.transferId)
      }
    },

    async pull(deviceId, remotePath, opts) {
      const path = validateRemotePath(remotePath)
      const maxPullBytes = deps.settings().maxPullBytes
      const backend = resolveBackend(deps, deviceId)
      const controller = begin(opts.transferId)
      try {
        const stream = await backend.adb.openRaw(backend.serial, 'sync:')
        try {
          // Enforcement #1 (plan 39 §3.6): refuse before any bytes move.
          const stat = await statRemote(stream, path)
          if (!stat) throw new EnkakuError('E_NOT_FOUND', `remote path does not exist: ${path}`)
          if (stat.size > maxPullBytes) {
            throw new EnkakuError('E_TRANSFER_TOO_LARGE', `the remote file is ${stat.size} bytes, exceeding the ${maxPullBytes}-byte pull limit`)
          }
          const label = path.split('/').pop() || 'pulled-file'
          const ext = label.includes('.') ? (label.split('.').pop() as string) : 'bin'
          const dest = devicePullArtifactPath(deps.dataDir, deviceId, label, ext)
          mkdirSync(dest.dir, { recursive: true })
          // Enforcement #2 (plan 39 §3.6): the running total is also checked
          // WHILE streaming, inside `pullFile` itself, so a file that grows
          // between the `stat` above and now still cannot exceed the cap.
          const { bytes } = await pullFile(stream, {
            remotePath: path,
            localPath: dest.abs,
            maxBytes: maxPullBytes,
            onProgress: opts.onProgress ? (received) => opts.onProgress?.(received, stat.size) : undefined,
            signal: controller.signal,
          })
          stream.close()
          const info = registerDeviceArtifact({ db: deps.db }, { deviceId, label, relPath: dest.rel, sizeBytes: bytes })
          return { artifactId: info.id, bytes }
        } catch (err) {
          stream.close(true)
          throw err
        }
      } finally {
        end(opts.transferId)
      }
    },

    async install(deviceId, artifactId, opts) {
      const artifact = await resolveArtifact(deps, artifactId)
      if (!/\.apk$/i.test(artifact.path)) {
        throw new EnkakuError('E_BAD_REQUEST', 'the artifact is not an .apk file')
      }
      const maxPushBytes = deps.settings().maxPushBytes
      if (artifact.sizeBytes > maxPushBytes) {
        throw new EnkakuError('E_TRANSFER_TOO_LARGE', `the artifact is ${artifact.sizeBytes} bytes, exceeding the ${maxPushBytes}-byte push limit`)
      }
      const remotePath = `/data/local/tmp/enkaku-${crypto.randomUUID()}.apk`
      const backend = resolveBackend(deps, deviceId)
      const controller = begin(opts.transferId)
      const startedAt = Date.now()
      try {
        const stream = await backend.adb.openRaw(backend.serial, 'sync:')
        try {
          await pushFile(stream, {
            localPath: artifact.abs,
            remotePath,
            onProgress: opts.onProgress ? (sent, total) => opts.onProgress?.(sent, total) : undefined,
            signal: controller.signal,
          })
          stream.close()
        } catch (err) {
          stream.close(true)
          throw err
        }

        const flags = [
          (opts.reinstall ?? true) ? '-r' : '',
          (opts.grantPermissions ?? true) ? '-g' : '',
          opts.allowDowngrade ? '-d' : '',
        ]
          .filter(Boolean)
          .join(' ')
        const cmd = `pm install ${flags} ${shellQuote(remotePath)}`.replace(/\s+/g, ' ').trim()
        const output = await runOnLane(backend, cmd, deps.settings().installTimeoutMs, controller.signal)
        const parsed = parseInstallOutput(output)
        if (!parsed.success) {
          throw new EnkakuError('E_INSTALL_FAILED', parsed.reason)
        }
        return { package: parsed.pkg, durationMs: Date.now() - startedAt, output: output.trim() }
      } finally {
        end(opts.transferId)
        // The staged APK is deleted in this `finally` on every exit path —
        // success, failure, AND cancel (plan 39 §4.2 step 4, acceptance #4).
        // Best-effort: a device that already lost its connection cannot
        // usefully surface a second error here.
        await backend.adb.exec(backend.serial, `rm -f ${shellQuote(remotePath)}`, { profile: 'appLifecycle' }).catch(() => {})
      }
    },
  }
}
